version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
# New Redis service
  redis:
    image: redis:latest 
    ports:
      - 6379:6379 
    volumes:
      - ./redis-data:/data  