import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme_provider";
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";
import validateInstallation from "@/utils/validate_installation";
import InstallGithubApp from "@/components/install_github_app";

// const inter = Inter({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const installation_id = await validateInstallation();

  return (
    <html lang="en">
      <body className={"min-h-screen flex flex-col"}>
        <SessionProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header/>
          <main className="flex flex-grow m-3 pt-12">
            {installation_id? children: <div className="flex flex-col items-center justify-center py-2 w-full">
              <p className="p-4 text-center">
                Hi!, {process.env.GITHUB_APP_NAME} app is not installed on your Github account or you are not connected to network. Please install or connect to internet to continue.
              </p>
              <InstallGithubApp />
              </div>}
          </main>
        </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}


