import type { Metadata } from 'next'

export async function generateMetadata() : Promise<Metadata> {
  return {
    title: "Toggler Page",
    description: "Generated by create next app",
  };
}

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center py-2 w-full">
     Hello.
    </div>
  );
}
